[package]
name = "whim"
version = "0.1.0"
authors = ["Jeff Schwab <jeff@unbuggy.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
warp = { path = "../../pkg/warp", version = "0.2", features = ["tls"] }

openssl = { version = "0.10", features = ["vendored"] }
