[package]
name = "whim"
version = "0.1.0"
authors = ["Jeff Schwab <jeff@unbuggy.com>"]
edition = "2018"

[dependencies]

# Serialization
serde = { version = "1.0", features = ["derive"] }

# Config parser
toml = "0.5"

# Web server
warp = { path = "../../pkg/warp", version = "0.2", features = ["tls"] }

# Async event framework
[dependencies.tokio]
version = "0.3"
features = ["fs", "macros", "process", "rt-multi-thread"]

